/* Generated by dev/firmware-data.cjs. Do not edit. */
(function(root){
'use strict';
const data = {
  "sourceHead": "09060c7177290e2c46d40c2c8850f536e12ac341",
  "fingerprints": {
    "src/content/ScenarioLoader.cpp": "cd38c69dffe368fe7d615690ed2473fcd3b6a9de4c202768adbc4afd396a3d12",
    "src/content/ScenarioImport.h": "dcd31b7464eb42b4224eae2db235b1baf12c0bdc57c5dbefc90eb00b96928001",
    "src/content/ScenarioLoader.h": "d1f183e9f1b45f0e324c21b42c8c7c49892fa4030ccd83936fbd6579efba468e",
    "src/content/ArchitectureDefinition.h": "a2ba2f348799894e9332c62ecd2231df145b821d5863490d8d0c5ff49f2d33a0",
    "src/content/ArchitectureFactory.cpp": "2f203266f8a9625b5c9043fb43060a047e5d9b188913cfdfe6870cab0d6c4211",
    "src/content/ScenarioScanner.cpp": "dd3c935322ff5026644246cbcf5cad1ad6cd42d2a2641801c99beed07219318c",
    "src/content/ScenarioScanner.h": "a3aee3ac3eedca32b0be45f8b693c5dc796423a620dabb4bb8cedfa74c96836b",
    "src/content/BlackIceRegistry.cpp": "cb0f7ae8b1f3d491f213394a6e597f5824c5ce627a75ea514404aff91913db70",
    "src/content/BlackIceRegistry.h": "04c3f7b3d21cbc6f3ef40df63bab6ee07f6f7bf8e002c474329e5b61e142ec11",
    "src/game/BlackIce.cpp": "22f89bbde359e231b2b7226eb942038c741315d83ed126c343e351fbda3ea5ac",
    "src/game/BlackIce.h": "e5999fc82d0711e7ce832793fbee173f3a268f8d4e1fafef83df02ea92be61c6",
    "src/content/DemonRegistry.cpp": "3a97b33bcfe87c4c1ea5982bf59aa5986e0b32b6f22a19b80175d9ddaa1c4e33",
    "src/content/DemonRegistry.h": "30241962a98462503ac9c8e9fec793b40582a30736f5cda3d4a02391bf813992",
    "src/game/Demon.cpp": "19cbbb405bf19ce112991c3600290eec1dae91af044e76fc110587e93e43f96a",
    "src/game/Demon.h": "0c342dc42a71a2acc813d34e98da3de328abffc24d07fd27432a629317407d39",
    "src/content/EnemyNetrunnerRegistry.cpp": "8e1f2e6ccd9494565890ef59a56bfa0cad5f569a307f497388220e8480690c45",
    "src/content/EnemyNetrunnerRegistry.h": "bc97c5bf95bede7e0aac015061143962f88292e04a86111ecebe265524f8b107",
    "src/game/EnemyNetrunner.cpp": "445ab9adee13b2eb85e99f4034d56321c1458f303db60fc9c837c7d96dc8035b",
    "src/game/EnemyNetrunner.h": "5cedd8454474061f2eb29ab422bff5d6ec19ef988326cae221052966383cfb01",
    "src/game/NetTypes.h": "df9bd595fd09032be260690e40b3a60f3b7527f8ea88f7cbe466b298b957e5a8",
    "src/game/VisualIds.h": "43f5be62daa48bdecc467627db987aa49b32fb66f0d1ddaa3c7e3dc2e875db22",
    "src/game/CyberdeckConfig.h": "79c67f1c120c3866055df7be39d4b20fc8b88316e97c046595c24e358a8eb302",
    "src/game/CyberdeckConfig.cpp": "bf254aa028033136abfef1150aea652f87c436c31caa91b5f27c880c8de0e04a",
    "src/game/ProgramCatalog.cpp": "fe0258e8298dd65f8d99c0d6c628789df4c79ed01dc8cd554768204be4a84513",
    "src/game/GameState.cpp": "58986149d587c6a4148dd2bd5a1f78c6085f3c073b981f585db1490c38f0e94b",
    "src/app/App.cpp": "91facd07cec88ce2b78f2376324f93b2d81435a8867e31ac3d2dbe7eea7e51ad",
    "src/ui/DisplayManager.cpp": "9f255ba7a415248eb16c78ffacbd802c8aeb4541e85dd73be8e897f9fb1a4db2",
    "src/ui/DisplayManager.h": "566d5d5e817d0bddef57c7bb76d3696e466703789081e201733b95f165447e6f",
    "src/ui/GameUIController.cpp": "cc768552e925cc10933bcf25e2b74db23db708888559b45e0c2933d59ccdb175",
    "src/ui/GameUIController.h": "dcc5660102c177e3a3687065b45be70aa3378983853f1ea63eb9a3af7faacc88"
  },
  "visuals": [
    "hound",
    "bird",
    "serpent",
    "octopus",
    "wraith",
    "hunter",
    "scorpion",
    "rat",
    "winged",
    "feline",
    "skull",
    "giant"
  ],
  "animations": [
    "lunge",
    "pulse",
    "slash",
    "burst"
  ],
  "demonVisuals": [
    {
      "id": "orb",
      "label": "Orb",
      "sprite": "demon1"
    },
    {
      "id": "sentinel",
      "label": "Sentinel",
      "sprite": "demon2"
    },
    {
      "id": "crown",
      "label": "Crown",
      "sprite": "demon3"
    }
  ],
  "demonAnimations": [
    "lunge",
    "pulse",
    "slash",
    "burst"
  ],
  "behaviors": [
    "direct_damage",
    "derezz_defender_damage",
    "destroy_installed_program",
    "navigation_lock_damage",
    "action_penalty_damage",
    "program_damage",
    "apply_fire",
    "move_penalty_damage",
    "stat_penalty",
    "unsafe_jack_out_damage"
  ],
  "sprites": {
    "hound": {
      "label": "Hound",
      "firmware": "Hound01",
      "renderer": "drawHound01",
      "commands": [
        [
          "fillTriangle",
          6,
          16,
          15,
          3,
          20,
          20,
          30720
        ],
        [
          "fillTriangle",
          42,
          16,
          33,
          3,
          28,
          20,
          30720
        ],
        [
          "fillRoundRect",
          7,
          14,
          34,
          25,
          7,
          63488
        ],
        [
          "fillTriangle",
          10,
          25,
          38,
          25,
          24,
          43,
          63488
        ],
        [
          "fillRoundRect",
          13,
          20,
          22,
          15,
          4,
          30720
        ],
        [
          "fillTriangle",
          17,
          29,
          31,
          29,
          24,
          39,
          30720
        ],
        [
          "fillRect",
          17,
          22,
          5,
          3,
          63519
        ],
        [
          "fillRect",
          27,
          22,
          5,
          3,
          63519
        ],
        [
          "fillTriangle",
          18,
          35,
          22,
          35,
          20,
          42,
          65535
        ],
        [
          "fillTriangle",
          27,
          35,
          31,
          35,
          29,
          42,
          65535
        ]
      ]
    },
    "bird": {
      "label": "Bird",
      "firmware": "Bird01",
      "renderer": "drawBird01",
      "commands": [
        [
          "fillTriangle",
          4,
          16,
          23,
          19,
          16,
          36,
          30720
        ],
        [
          "fillTriangle",
          44,
          16,
          25,
          19,
          32,
          36,
          30720
        ],
        [
          "fillTriangle",
          0,
          10,
          22,
          17,
          17,
          31,
          63488
        ],
        [
          "fillTriangle",
          48,
          10,
          26,
          17,
          31,
          31,
          63488
        ],
        [
          "fillCircle",
          23,
          20,
          9,
          63488
        ],
        [
          "fillTriangle",
          28,
          18,
          41,
          22,
          29,
          27,
          63488
        ],
        [
          "fillCircle",
          23,
          20,
          5,
          30720
        ],
        [
          "fillCircle",
          26,
          19,
          2,
          63519
        ]
      ]
    },
    "serpent": {
      "label": "Serpent",
      "firmware": "Serpent01",
      "renderer": "drawSerpent01",
      "commands": [
        [
          "fillCircle",
          36,
          42,
          5,
          30720
        ],
        [
          "fillCircle",
          28,
          37,
          7,
          30720
        ],
        [
          "fillCircle",
          20,
          30,
          7,
          63488
        ],
        [
          "fillCircle",
          18,
          21,
          7,
          63488
        ],
        [
          "fillCircle",
          25,
          14,
          7,
          63488
        ],
        [
          "fillTriangle",
          25,
          10,
          36,
          3,
          38,
          14,
          63488
        ],
        [
          "fillCircle",
          32,
          9,
          5,
          30720
        ],
        [
          "fillCircle",
          34,
          8,
          2,
          63519
        ],
        [
          "drawFastHLine",
          24,
          16,
          5,
          63519
        ]
      ]
    },
    "octopus": {
      "label": "Octopus",
      "firmware": "Octopus01",
      "renderer": "drawOctopus01",
      "commands": [
        [
          "drawLine",
          14,
          26,
          3,
          43,
          30720
        ],
        [
          "drawLine",
          15,
          26,
          4,
          43,
          30720
        ],
        [
          "drawLine",
          20,
          29,
          12,
          46,
          30720
        ],
        [
          "drawLine",
          21,
          29,
          13,
          46,
          30720
        ],
        [
          "drawLine",
          28,
          29,
          29,
          47,
          30720
        ],
        [
          "drawLine",
          29,
          29,
          30,
          47,
          30720
        ],
        [
          "drawLine",
          34,
          26,
          45,
          43,
          30720
        ],
        [
          "drawLine",
          35,
          26,
          46,
          43,
          30720
        ],
        [
          "fillCircle",
          26,
          20,
          14,
          30720
        ],
        [
          "fillCircle",
          22,
          17,
          14,
          63488
        ],
        [
          "fillRoundRect",
          13,
          10,
          19,
          16,
          7,
          30720
        ],
        [
          "fillCircle",
          22,
          17,
          6,
          63488
        ],
        [
          "fillCircle",
          22,
          17,
          2,
          63519
        ]
      ]
    },
    "wraith": {
      "label": "Wraith",
      "firmware": "Wraith01",
      "renderer": "drawWraith01",
      "commands": [
        [
          "fillCircle",
          24,
          25,
          12,
          63488
        ],
        [
          "fillCircle",
          24,
          25,
          8,
          30720
        ],
        [
          "fillCircle",
          24,
          25,
          4,
          63488
        ],
        [
          "fillCircle",
          24,
          25,
          2,
          63519
        ],
        [
          "fillCircle",
          10,
          14,
          2,
          63488
        ],
        [
          "fillCircle",
          38,
          11,
          2,
          63488
        ],
        [
          "fillCircle",
          41,
          37,
          2,
          63488
        ]
      ]
    },
    "hunter": {
      "label": "Hunter",
      "firmware": "Hunter01",
      "renderer": "drawHunter01",
      "commands": [
        [
          "fillRoundRect",
          11,
          20,
          28,
          20,
          5,
          30720
        ],
        [
          "fillRect",
          35,
          24,
          10,
          9,
          30720
        ],
        [
          "fillRoundRect",
          15,
          5,
          18,
          18,
          4,
          63488
        ],
        [
          "fillRoundRect",
          12,
          19,
          24,
          18,
          4,
          63488
        ],
        [
          "fillRect",
          18,
          9,
          12,
          7,
          30720
        ],
        [
          "fillRect",
          16,
          24,
          16,
          9,
          30720
        ],
        [
          "fillRect",
          21,
          26,
          6,
          4,
          63519
        ],
        [
          "drawLine",
          38,
          28,
          45,
          20,
          63519
        ]
      ]
    },
    "scorpion": {
      "label": "Scorpion",
      "firmware": "Scorp01",
      "renderer": "drawScorp01",
      "commands": [
        [
          "drawLine",
          28,
          30,
          42,
          19,
          30720
        ],
        [
          "drawLine",
          42,
          19,
          45,
          6,
          30720
        ],
        [
          "fillTriangle",
          41,
          7,
          47,
          6,
          43,
          16,
          63519
        ],
        [
          "fillCircle",
          24,
          31,
          12,
          30720
        ],
        [
          "fillCircle",
          19,
          26,
          15,
          63488
        ],
        [
          "drawLine",
          11,
          24,
          3,
          17,
          63488
        ],
        [
          "drawLine",
          26,
          24,
          36,
          17,
          63488
        ],
        [
          "drawLine",
          12,
          34,
          5,
          43,
          63488
        ],
        [
          "drawLine",
          26,
          34,
          35,
          43,
          63488
        ],
        [
          "fillRoundRect",
          11,
          19,
          17,
          14,
          5,
          30720
        ],
        [
          "fillRoundRect",
          13,
          18,
          14,
          10,
          4,
          63488
        ],
        [
          "fillCircle",
          22,
          23,
          3,
          63519
        ]
      ]
    },
    "rat": {
      "label": "Rat",
      "firmware": "Rat01",
      "renderer": "drawRat01",
      "commands": [
        [
          "fillTriangle",
          13,
          31,
          2,
          3,
          18,
          10,
          30720
        ],
        [
          "fillTriangle",
          15,
          29,
          6,
          7,
          20,
          13,
          63488
        ],
        [
          "fillEllipse",
          23,
          30,
          19,
          10,
          63488
        ],
        [
          "fillCircle",
          38,
          24,
          8,
          63488
        ],
        [
          "fillEllipse",
          22,
          30,
          12,
          6,
          30720
        ],
        [
          "fillRect",
          19,
          25,
          7,
          10,
          63519
        ],
        [
          "fillCircle",
          39,
          23,
          2,
          63519
        ]
      ]
    },
    "winged": {
      "label": "Winged",
      "firmware": "Winged01",
      "renderer": "drawWinged01",
      "commands": [
        [
          "fillTriangle",
          4,
          22,
          21,
          4,
          19,
          34,
          30720
        ],
        [
          "fillTriangle",
          44,
          22,
          27,
          4,
          29,
          34,
          30720
        ],
        [
          "fillTriangle",
          11,
          18,
          24,
          2,
          37,
          18,
          63488
        ],
        [
          "fillRoundRect",
          12,
          16,
          24,
          18,
          6,
          63488
        ],
        [
          "fillTriangle",
          15,
          30,
          33,
          30,
          24,
          42,
          63488
        ],
        [
          "fillTriangle",
          17,
          21,
          24,
          12,
          31,
          21,
          30720
        ],
        [
          "fillRect",
          18,
          25,
          12,
          5,
          30720
        ],
        [
          "fillCircle",
          24,
          19,
          2,
          63519
        ]
      ]
    },
    "feline": {
      "label": "Feline",
      "firmware": "Feline01",
      "renderer": "drawFeline01",
      "commands": [
        [
          "fillEllipse",
          26,
          26,
          21,
          16,
          30720
        ],
        [
          "fillTriangle",
          7,
          14,
          18,
          10,
          17,
          25,
          30720
        ],
        [
          "fillTriangle",
          41,
          14,
          30,
          10,
          31,
          25,
          30720
        ],
        [
          "fillEllipse",
          23,
          23,
          20,
          15,
          63488
        ],
        [
          "fillEllipse",
          23,
          24,
          14,
          10,
          30720
        ],
        [
          "fillRect",
          14,
          20,
          6,
          3,
          63519
        ],
        [
          "fillRect",
          26,
          20,
          6,
          3,
          63519
        ],
        [
          "fillTriangle",
          15,
          31,
          21,
          31,
          18,
          44,
          65535
        ],
        [
          "fillTriangle",
          26,
          31,
          32,
          31,
          29,
          44,
          65535
        ]
      ]
    },
    "skull": {
      "label": "Skull",
      "firmware": "Skull01",
      "renderer": "drawSkull01",
      "commands": [
        [
          "fillCircle",
          24,
          23,
          17,
          63488
        ],
        [
          "fillRect",
          16,
          25,
          16,
          13,
          63488
        ],
        [
          "fillCircle",
          24,
          23,
          12,
          30720
        ],
        [
          "fillRect",
          18,
          18,
          4,
          6,
          0
        ],
        [
          "fillRect",
          27,
          18,
          4,
          6,
          0
        ],
        [
          "fillCircle",
          24,
          29,
          3,
          63519
        ],
        [
          "drawFastHLine",
          18,
          34,
          12,
          30720
        ]
      ]
    },
    "giant": {
      "label": "Giant",
      "firmware": "BigGuy01",
      "renderer": "drawBigGuy01",
      "commands": [
        [
          "fillRect",
          7,
          7,
          34,
          31,
          30720
        ],
        [
          "fillRect",
          4,
          20,
          40,
          17,
          30720
        ],
        [
          "fillRect",
          9,
          4,
          30,
          18,
          63488
        ],
        [
          "fillRect",
          4,
          20,
          40,
          16,
          63488
        ],
        [
          "fillRect",
          9,
          35,
          13,
          11,
          63488
        ],
        [
          "fillRect",
          27,
          35,
          13,
          11,
          63488
        ],
        [
          "fillRect",
          15,
          9,
          18,
          9,
          30720
        ],
        [
          "fillRect",
          12,
          24,
          24,
          9,
          30720
        ],
        [
          "fillRect",
          20,
          26,
          8,
          4,
          63519
        ]
      ]
    },
    "enemy": {
      "label": "Enemy bust (fixed)",
      "renderer": "drawEnemyNetrunner",
      "commands": [
        [
          "fillRoundRect",
          49,
          37,
          32,
          29,
          7,
          31727
        ],
        [
          "fillRect",
          45,
          62,
          40,
          11,
          31727
        ],
        [
          "fillRoundRect",
          46,
          34,
          32,
          29,
          7,
          63488
        ],
        [
          "fillRect",
          42,
          60,
          40,
          11,
          63488
        ],
        [
          "drawRoundRect",
          51,
          41,
          22,
          11,
          3,
          0
        ],
        [
          "drawFastHLine",
          54,
          45,
          16,
          65535
        ],
        [
          "drawFastVLine",
          74,
          43,
          8,
          31727
        ],
        [
          "fillCircle",
          49,
          54,
          3,
          63519
        ],
        [
          "fillCircle",
          78,
          53,
          4,
          31727
        ],
        [
          "drawPixel",
          78,
          52,
          63519
        ],
        [
          "drawLine",
          46,
          50,
          40,
          55,
          63488
        ],
        [
          "drawFastHLine",
          78,
          57,
          7,
          63488
        ],
        [
          "drawPixel",
          87,
          57,
          63488
        ]
      ]
    },
    "demon0": {
      "label": "Demon actor (fixed)",
      "renderer": "drawDemonActor",
      "commands": [
        [
          "fillCircle",
          0,
          12,
          10,
          63488
        ],
        [
          "fillCircle",
          -3,
          9,
          4,
          63519
        ],
        [
          "drawLine",
          -7,
          5,
          -12,
          0,
          63488
        ],
        [
          "drawLine",
          -12,
          0,
          -8,
          9,
          63488
        ],
        [
          "drawLine",
          7,
          5,
          12,
          0,
          63488
        ],
        [
          "drawLine",
          12,
          0,
          8,
          9,
          63488
        ],
        [
          "drawPixel",
          -4,
          11,
          65535
        ],
        [
          "drawPixel",
          4,
          11,
          65535
        ],
        [
          "drawCircle",
          0,
          12,
          4,
          0
        ],
        [
          "drawPixel",
          0,
          12,
          65535
        ]
      ]
    },
    "demon1": {
      "label": "Demon actor (fixed)",
      "renderer": "drawDemonActor",
      "commands": [
        [
          "fillCircle",
          0,
          12,
          10,
          63488
        ],
        [
          "fillCircle",
          -3,
          9,
          4,
          63519
        ],
        [
          "drawLine",
          -7,
          5,
          -12,
          0,
          63488
        ],
        [
          "drawLine",
          -12,
          0,
          -8,
          9,
          63488
        ],
        [
          "drawLine",
          7,
          5,
          12,
          0,
          63488
        ],
        [
          "drawLine",
          12,
          0,
          8,
          9,
          63488
        ],
        [
          "drawPixel",
          -4,
          11,
          65535
        ],
        [
          "drawPixel",
          4,
          11,
          65535
        ],
        [
          "drawCircle",
          0,
          12,
          4,
          0
        ],
        [
          "drawPixel",
          0,
          12,
          65535
        ]
      ]
    },
    "demon2": {
      "label": "Demon actor (fixed)",
      "renderer": "drawDemonActor",
      "commands": [
        [
          "fillRect",
          -6,
          7,
          12,
          19,
          63488
        ],
        [
          "fillCircle",
          0,
          4,
          6,
          63519
        ],
        [
          "fillRect",
          -7,
          -1,
          14,
          4,
          63488
        ],
        [
          "drawRect",
          -3,
          9,
          6,
          9,
          0
        ],
        [
          "drawFastHLine",
          -4,
          21,
          8,
          65535
        ],
        [
          "drawLine",
          8,
          13,
          13,
          22,
          65535
        ]
      ]
    },
    "demon3": {
      "label": "Demon actor (fixed)",
      "renderer": "drawDemonActor",
      "commands": [
        [
          "fillRect",
          -12,
          6,
          24,
          19,
          63488
        ],
        [
          "drawRect",
          -9,
          0,
          18,
          9,
          63519
        ],
        [
          "drawRect",
          -5,
          11,
          10,
          7,
          0
        ],
        [
          "drawFastHLine",
          -8,
          21,
          16,
          65535
        ],
        [
          "drawLine",
          -10,
          23,
          -20,
          30,
          2016
        ],
        [
          "drawLine",
          -5,
          23,
          -10,
          30,
          2016
        ],
        [
          "drawLine",
          0,
          23,
          0,
          30,
          2016
        ],
        [
          "drawLine",
          5,
          23,
          10,
          30,
          2016
        ],
        [
          "drawLine",
          10,
          23,
          20,
          30,
          2016
        ]
      ]
    }
  },
  "builtins": {
    "black_ice": [
      {
        "id": "ice_01",
        "name": "TRACEJACKAL",
        "visual": "hound",
        "animation": "lunge"
      },
      {
        "id": "ice_02",
        "name": "CARRIONBYTE",
        "visual": "bird",
        "animation": "pulse"
      },
      {
        "id": "ice_03",
        "name": "NEEDLECOIL",
        "visual": "serpent",
        "animation": "slash"
      },
      {
        "id": "ice_04",
        "name": "DEADLOCK",
        "visual": "octopus",
        "animation": "lunge"
      },
      {
        "id": "ice_05",
        "name": "GHOSTPULSE",
        "visual": "wraith",
        "animation": "burst"
      },
      {
        "id": "ice_06",
        "name": "PACKETSAW",
        "visual": "hunter",
        "animation": "slash"
      },
      {
        "id": "ice_07",
        "name": "STINGWIRE",
        "visual": "scorpion",
        "animation": "burst"
      },
      {
        "id": "ice_08",
        "name": "GUTTERMESH",
        "visual": "rat",
        "animation": "pulse"
      },
      {
        "id": "ice_09",
        "name": "STORMRAZOR",
        "visual": "winged",
        "animation": "slash"
      },
      {
        "id": "ice_10",
        "name": "GLASSCAT",
        "visual": "feline",
        "animation": "lunge"
      },
      {
        "id": "ice_11",
        "name": "GREYMARK",
        "visual": "skull",
        "animation": "pulse"
      },
      {
        "id": "ice_12",
        "name": "BREACHER",
        "visual": "giant",
        "animation": "lunge"
      }
    ],
    "demons": [
      {
        "id": "demon_01",
        "name": "LATCH",
        "visual": "orb"
      },
      {
        "id": "demon_02",
        "name": "WARDEN",
        "visual": "sentinel"
      },
      {
        "id": "demon_03",
        "name": "CROWN",
        "visual": "crown"
      }
    ],
    "enemies": [
      {
        "id": "nullbyte",
        "handle": "NULLBYTE",
        "visual": "enemy"
      },
      {
        "id": "zer=0",
        "handle": "Zer=0",
        "visual": "enemy"
      }
    ]
  },
  "programs": [
    {
      "name": "Sword",
      "type": "Attacker",
      "slots": 1
    },
    {
      "name": "Banhammer",
      "type": "Attacker",
      "slots": 1
    },
    {
      "name": "Armor",
      "type": "Defender",
      "slots": 1
    },
    {
      "name": "Flak",
      "type": "Defender",
      "slots": 1
    },
    {
      "name": "Shield",
      "type": "Defender",
      "slots": 1
    },
    {
      "name": "Eraser",
      "type": "Booster",
      "slots": 1
    },
    {
      "name": "See Ya",
      "type": "Booster",
      "slots": 1
    },
    {
      "name": "Speedy Gonzalvez",
      "type": "Booster",
      "slots": 1
    },
    {
      "name": "Worm",
      "type": "Booster",
      "slots": 1
    },
    {
      "name": "DeckKRASH",
      "type": "Attacker",
      "slots": 1
    },
    {
      "name": "Hellbolt",
      "type": "Attacker",
      "slots": 1
    },
    {
      "name": "Nervescrub",
      "type": "Attacker",
      "slots": 1
    },
    {
      "name": "Poison Flatline",
      "type": "Attacker",
      "slots": 1
    },
    {
      "name": "Superglue",
      "type": "Attacker",
      "slots": 1
    },
    {
      "name": "Vrizzbolt",
      "type": "Attacker",
      "slots": 1
    }
  ]
};
if(typeof module==='object' && module.exports) module.exports=data;
else root.NRData=data;
})(typeof globalThis!=='undefined'?globalThis:this);
